const products = [
  {
    id: 1,
    title: "Product 1",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 1",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 406558,
    instock: true,
  },
  {
    id: 2,
    title: "Product 2",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 2",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 140498,
    instock: true,
  },
  {
    id: 3,
    title: "Product 3",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 3",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 364171,
    instock: true,
  },
  {
    id: 4,
    title: "Product 4",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 4",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 949962,
    instock: true,
  },
  {
    id: 5,
    title: "Product 5",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 5",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 829538,
    instock: true,
  },
  {
    id: 6,
    title: "Product 6",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 6",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 382860,
    instock: true,
  },
  {
    id: 7,
    title: "Product 7",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 7",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 168256,
    instock: true,
  },
  {
    id: 8,
    title: "Product 8",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 8",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 376260,
    instock: true,
  },
  {
    id: 9,
    title: "Product 9",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 9",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 261993,
    instock: true,
  },
  {
    id: 10,
    title: "Product 10",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 10",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 779439,
    instock: true,
  },
  {
    id: 11,
    title: "Product 11",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 11",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 814413,
    instock: true,
  },
  {
    id: 12,
    title: "Product 12",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 12",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 891606,
    instock: true,
  },
  {
    id: 13,
    title: "Product 13",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 13",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 851408,
    instock: true,
  },
  {
    id: 14,
    title: "Product 14",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 14",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 414995,
    instock: true,
  },
  {
    id: 15,
    title: "Product 15",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 15",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 532494,
    instock: true,
  },
  {
    id: 16,
    title: "Product 16",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 16",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 393415,
    instock: true,
  },
  {
    id: 17,
    title: "Product 17",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 17",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 206562,
    instock: true,
  },
  {
    id: 18,
    title: "Product 18",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 18",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 256724,
    instock: true,
  },
  {
    id: 19,
    title: "Product 19",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 19",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 255242,
    instock: true,
  },
  {
    id: 20,
    title: "Product 20",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 20",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 349159,
    instock: true,
  },
  {
    id: 21,
    title: "Product 21",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 21",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 971943,
    instock: true,
  },
  {
    id: 22,
    title: "Product 22",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 22",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 942963,
    instock: true,
  },
  {
    id: 23,
    title: "Product 23",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 23",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 165356,
    instock: true,
  },
  {
    id: 24,
    title: "Product 24",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 24",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 792489,
    instock: true,
  },
  {
    id: 25,
    title: "Product 25",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 25",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 347727,
    instock: true,
  },
  {
    id: 26,
    title: "Product 26",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 26",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 988437,
    instock: true,
  },
  {
    id: 27,
    title: "Product 27",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 27",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 359567,
    instock: true,
  },
  {
    id: 28,
    title: "Product 28",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 28",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 170397,
    instock: true,
  },
  {
    id: 29,
    title: "Product 29",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 29",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 170801,
    instock: true,
  },
  {
    id: 30,
    title: "Product 30",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 30",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 971808,
    instock: true,
  },
  {
    id: 31,
    title: "Product 31",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 31",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 359893,
    instock: true,
  },
  {
    id: 32,
    title: "Product 32",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 32",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 461059,
    instock: true,
  },
  {
    id: 33,
    title: "Product 33",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 33",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 383884,
    instock: true,
  },
  {
    id: 34,
    title: "Product 34",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 34",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 232222,
    instock: true,
  },
  {
    id: 35,
    title: "Product 35",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 35",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 292479,
    instock: true,
  },
  {
    id: 36,
    title: "Product 36",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 36",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 322088,
    instock: true,
  },
  {
    id: 37,
    title: "Product 37",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 37",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 750856,
    instock: true,
  },
  {
    id: 38,
    title: "Product 38",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 38",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 815847,
    instock: true,
  },
  {
    id: 39,
    title: "Product 39",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 39",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 481219,
    instock: true,
  },
  {
    id: 40,
    title: "Product 40",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 40",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 382004,
    instock: true,
  },
  {
    id: 41,
    title: "Product 41",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 41",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 557487,
    instock: true,
  },
  {
    id: 42,
    title: "Product 42",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 42",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 139654,
    instock: true,
  },
  {
    id: 43,
    title: "Product 43",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 43",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 467323,
    instock: true,
  },
  {
    id: 44,
    title: "Product 44",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 44",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 789463,
    instock: true,
  },
  {
    id: 45,
    title: "Product 45",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 45",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 286172,
    instock: true,
  },
  {
    id: 46,
    title: "Product 46",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 46",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 375976,
    instock: true,
  },
  {
    id: 47,
    title: "Product 47",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 47",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 520488,
    instock: true,
  },
  {
    id: 48,
    title: "Product 48",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 48",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 756073,
    instock: true,
  },
  {
    id: 49,
    title: "Product 49",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 49",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 401204,
    instock: true,
  },
  {
    id: 50,
    title: "Product 50",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 50",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 493916,
    instock: true,
  },
  {
    id: 51,
    title: "Product 51",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 51",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 626797,
    instock: true,
  },
  {
    id: 52,
    title: "Product 52",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 52",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 976649,
    instock: true,
  },
  {
    id: 53,
    title: "Product 53",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 53",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 689528,
    instock: true,
  },
  {
    id: 54,
    title: "Product 54",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 54",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 203613,
    instock: true,
  },
  {
    id: 55,
    title: "Product 55",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 55",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 553099,
    instock: true,
  },
  {
    id: 56,
    title: "Product 56",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 56",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 830086,
    instock: true,
  },
  {
    id: 57,
    title: "Product 57",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 57",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 985900,
    instock: true,
  },
  {
    id: 58,
    title: "Product 58",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 58",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 384021,
    instock: true,
  },
  {
    id: 59,
    title: "Product 59",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 59",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 278838,
    instock: true,
  },
  {
    id: 60,
    title: "Product 60",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 60",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 387106,
    instock: true,
  },
  {
    id: 61,
    title: "Product 61",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 61",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 550089,
    instock: true,
  },
  {
    id: 62,
    title: "Product 62",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 62",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 232880,
    instock: true,
  },
  {
    id: 63,
    title: "Product 63",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 63",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 937562,
    instock: true,
  },
  {
    id: 64,
    title: "Product 64",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 64",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 477443,
    instock: true,
  },
  {
    id: 65,
    title: "Product 65",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 65",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 595626,
    instock: true,
  },
  {
    id: 66,
    title: "Product 66",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 66",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 443304,
    instock: true,
  },
  {
    id: 67,
    title: "Product 67",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 67",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 264966,
    instock: true,
  },
  {
    id: 68,
    title: "Product 68",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 68",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 926211,
    instock: true,
  },
  {
    id: 69,
    title: "Product 69",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 69",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 922462,
    instock: true,
  },
  {
    id: 70,
    title: "Product 70",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 70",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 572918,
    instock: true,
  },
  {
    id: 71,
    title: "Product 71",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 71",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 847302,
    instock: true,
  },
  {
    id: 72,
    title: "Product 72",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 72",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 224298,
    instock: true,
  },
  {
    id: 73,
    title: "Product 73",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 73",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 464148,
    instock: true,
  },
  {
    id: 74,
    title: "Product 74",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 74",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 414674,
    instock: true,
  },
  {
    id: 75,
    title: "Product 75",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 75",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 848578,
    instock: true,
  },
];

module.exports = products;
