const products = [
  {
    id: 1,
    title: "Product 1",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 1",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 406558,
    instock: true,
  },
  {
    id: 2,
    title: "Product 2",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 2",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 140498,
    instock: true,
  },
  {
    id: 3,
    title: "Product 3",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 3",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 364171,
    instock: true,
  },
  {
    id: 4,
    title: "Product 4",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 4",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 949962,
    instock: true,
  },
  {
    id: 5,
    title: "Product 5",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 5",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 829538,
    instock: true,
  },
  {
    id: 6,
    title: "Product 6",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 6",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 382860,
    instock: true,
  },
  {
    id: 7,
    title: "Product 7",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 7",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 168256,
    instock: true,
  },
  {
    id: 8,
    title: "Product 8",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 8",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 376260,
    instock: true,
  },
  {
    id: 9,
    title: "Product 9",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 9",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 261993,
    instock: true,
  },
  {
    id: 10,
    title: "Product 10",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 10",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 779439,
    instock: true,
  },
  {
    id: 11,
    title: "Product 11",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 11",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 814413,
    instock: true,
  },
  {
    id: 12,
    title: "Product 12",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 12",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 891606,
    instock: true,
  },
  {
    id: 13,
    title: "Product 13",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 13",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 851408,
    instock: true,
  },
  {
    id: 14,
    title: "Product 14",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 14",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 414995,
    instock: true,
  },
  {
    id: 15,
    title: "Product 15",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 15",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 532494,
    instock: true,
  },
  {
    id: 16,
    title: "Product 16",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 16",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 393415,
    instock: true,
  },
  {
    id: 17,
    title: "Product 17",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 17",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 206562,
    instock: true,
  },
  {
    id: 18,
    title: "Product 18",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 18",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 256724,
    instock: true,
  },
  {
    id: 19,
    title: "Product 19",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 19",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 255242,
    instock: true,
  },
  {
    id: 20,
    title: "Product 20",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 20",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 349159,
    instock: true,
  },
  {
    id: 21,
    title: "Product 21",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 21",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 971943,
    instock: true,
  },
  {
    id: 22,
    title: "Product 22",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 22",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 942963,
    instock: true,
  },
  {
    id: 23,
    title: "Product 23",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 23",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 165356,
    instock: true,
  },
  {
    id: 24,
    title: "Product 24",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 24",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 792489,
    instock: true,
  },
  {
    id: 25,
    title: "Product 25",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 25",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 347727,
    instock: true,
  },
  {
    id: 26,
    title: "Product 26",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 26",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 988437,
    instock: true,
  },
  {
    id: 27,
    title: "Product 27",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 27",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 359567,
    instock: true,
  },
  {
    id: 28,
    title: "Product 28",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 28",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 170397,
    instock: true,
  },
  {
    id: 29,
    title: "Product 29",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 29",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 170801,
    instock: true,
  },
  {
    id: 30,
    title: "Product 30",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 30",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 971808,
    instock: true,
  },
  {
    id: 31,
    title: "Product 31",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 31",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 359893,
    instock: true,
  },
  {
    id: 32,
    title: "Product 32",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 32",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 461059,
    instock: true,
  },
  {
    id: 33,
    title: "Product 33",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 33",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 383884,
    instock: true,
  },
  {
    id: 34,
    title: "Product 34",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 34",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 232222,
    instock: true,
  },
  {
    id: 35,
    title: "Product 35",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 35",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 292479,
    instock: true,
  },
  {
    id: 36,
    title: "Product 36",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 36",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 322088,
    instock: true,
  },
  {
    id: 37,
    title: "Product 37",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 37",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 750856,
    instock: true,
  },
  {
    id: 38,
    title: "Product 38",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 38",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 815847,
    instock: true,
  },
  {
    id: 39,
    title: "Product 39",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 39",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 481219,
    instock: true,
  },
  {
    id: 40,
    title: "Product 40",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 40",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 382004,
    instock: true,
  },
  {
    id: 41,
    title: "Product 41",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 41",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 557487,
    instock: true,
  },
  {
    id: 42,
    title: "Product 42",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 42",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 139654,
    instock: true,
  },
  {
    id: 43,
    title: "Product 43",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 43",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 467323,
    instock: true,
  },
  {
    id: 44,
    title: "Product 44",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 44",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 789463,
    instock: true,
  },
  {
    id: 45,
    title: "Product 45",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 45",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 286172,
    instock: true,
  },
  {
    id: 46,
    title: "Product 46",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 46",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 375976,
    instock: true,
  },
  {
    id: 47,
    title: "Product 47",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 47",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 520488,
    instock: true,
  },
  {
    id: 48,
    title: "Product 48",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 48",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 756073,
    instock: true,
  },
  {
    id: 49,
    title: "Product 49",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 49",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 401204,
    instock: true,
  },
  {
    id: 50,
    title: "Product 50",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 50",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 493916,
    instock: true,
  },
  {
    id: 51,
    title: "Product 51",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 51",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 626797,
    instock: true,
  },
  {
    id: 52,
    title: "Product 52",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 52",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 976649,
    instock: true,
  },
  {
    id: 53,
    title: "Product 53",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 53",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 689528,
    instock: true,
  },
  {
    id: 54,
    title: "Product 54",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 54",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 203613,
    instock: true,
  },
  {
    id: 55,
    title: "Product 55",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 55",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 553099,
    instock: true,
  },
  {
    id: 56,
    title: "Product 56",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 56",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 830086,
    instock: true,
  },
  {
    id: 57,
    title: "Product 57",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 57",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 985900,
    instock: true,
  },
  {
    id: 58,
    title: "Product 58",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 58",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 384021,
    instock: true,
  },
  {
    id: 59,
    title: "Product 59",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 59",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 278838,
    instock: true,
  },
  {
    id: 60,
    title: "Product 60",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 60",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 387106,
    instock: true,
  },
  {
    id: 61,
    title: "Product 61",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 61",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 550089,
    instock: true,
  },
  {
    id: 62,
    title: "Product 62",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 62",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 232880,
    instock: true,
  },
  {
    id: 63,
    title: "Product 63",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 63",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 937562,
    instock: true,
  },
  {
    id: 64,
    title: "Product 64",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 64",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 477443,
    instock: true,
  },
  {
    id: 65,
    title: "Product 65",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 65",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 595626,
    instock: true,
  },
  {
    id: 66,
    title: "Product 66",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 66",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 443304,
    instock: true,
  },
  {
    id: 67,
    title: "Product 67",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 67",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 264966,
    instock: true,
  },
  {
    id: 68,
    title: "Product 68",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 68",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 926211,
    instock: true,
  },
  {
    id: 69,
    title: "Product 69",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 69",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 922462,
    instock: true,
  },
  {
    id: 70,
    title: "Product 70",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 70",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 572918,
    instock: true,
  },
  {
    id: 71,
    title: "Product 71",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 71",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 847302,
    instock: true,
  },
  {
    id: 72,
    title: "Product 72",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 72",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 224298,
    instock: true,
  },
  {
    id: 73,
    title: "Product 73",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 73",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 464148,
    instock: true,
  },
  {
    id: 74,
    title: "Product 74",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 74",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 414674,
    instock: true,
  },
  {
    id: 75,
    title: "Product 75",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 75",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 848578,
    instock: true,
  },
  {
    id: 76,
    title: "Product 76",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 76",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 800593,
    instock: true,
  },
  {
    id: 77,
    title: "Product 77",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 77",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 941570,
    instock: true,
  },
  {
    id: 78,
    title: "Product 78",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 78",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 738743,
    instock: true,
  },
  {
    id: 79,
    title: "Product 79",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 79",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 836287,
    instock: true,
  },
  {
    id: 80,
    title: "Product 80",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 80",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 729417,
    instock: true,
  },
  {
    id: 81,
    title: "Product 81",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 81",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 699857,
    instock: true,
  },
  {
    id: 82,
    title: "Product 82",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 82",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 619230,
    instock: true,
  },
  {
    id: 83,
    title: "Product 83",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 83",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 995971,
    instock: true,
  },
  {
    id: 84,
    title: "Product 84",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 84",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 986964,
    instock: true,
  },
  {
    id: 85,
    title: "Product 85",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 85",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 147878,
    instock: true,
  },
  {
    id: 86,
    title: "Product 86",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 86",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 260565,
    instock: true,
  },
  {
    id: 87,
    title: "Product 87",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 87",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 749719,
    instock: true,
  },
  {
    id: 88,
    title: "Product 88",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 88",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 601226,
    instock: true,
  },
  {
    id: 89,
    title: "Product 89",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 89",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 642429,
    instock: true,
  },
  {
    id: 90,
    title: "Product 90",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 90",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 431100,
    instock: true,
  },
  {
    id: 91,
    title: "Product 91",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 91",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 912807,
    instock: true,
  },
  {
    id: 92,
    title: "Product 92",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 92",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 566893,
    instock: true,
  },
  {
    id: 93,
    title: "Product 93",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 93",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 700066,
    instock: true,
  },
  {
    id: 94,
    title: "Product 94",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 94",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 552862,
    instock: true,
  },
  {
    id: 95,
    title: "Product 95",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 95",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 833407,
    instock: true,
  },
  {
    id: 96,
    title: "Product 96",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 96",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 533847,
    instock: true,
  },
  {
    id: 97,
    title: "Product 97",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 97",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 838347,
    instock: true,
  },
  {
    id: 98,
    title: "Product 98",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 98",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 582369,
    instock: true,
  },
  {
    id: 99,
    title: "Product 99",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 99",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 667905,
    instock: true,
  },
  {
    id: 100,
    title: "Product 100",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 100",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 306052,
    instock: true,
  },
  {
    id: 101,
    title: "Product 101",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 101",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 559401,
    instock: true,
  },
  {
    id: 102,
    title: "Product 102",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 102",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 162802,
    instock: true,
  },
  {
    id: 103,
    title: "Product 103",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 103",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 861127,
    instock: true,
  },
  {
    id: 104,
    title: "Product 104",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 104",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 803469,
    instock: true,
  },
  {
    id: 105,
    title: "Product 105",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 105",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 375029,
    instock: true,
  },
  {
    id: 106,
    title: "Product 106",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 106",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 583869,
    instock: true,
  },
  {
    id: 107,
    title: "Product 107",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 107",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 608272,
    instock: true,
  },
  {
    id: 108,
    title: "Product 108",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 108",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 115549,
    instock: true,
  },
  {
    id: 109,
    title: "Product 109",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 109",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 997228,
    instock: true,
  },
  {
    id: 110,
    title: "Product 110",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 110",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 882255,
    instock: true,
  },
  {
    id: 111,
    title: "Product 111",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 111",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 511643,
    instock: true,
  },
  {
    id: 112,
    title: "Product 112",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 112",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 282908,
    instock: true,
  },
  {
    id: 113,
    title: "Product 113",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 113",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 420102,
    instock: true,
  },
  {
    id: 114,
    title: "Product 114",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 114",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 937943,
    instock: true,
  },
  {
    id: 115,
    title: "Product 115",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 115",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 433844,
    instock: true,
  },
  {
    id: 116,
    title: "Product 116",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 116",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 407940,
    instock: true,
  },
  {
    id: 117,
    title: "Product 117",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 117",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 570494,
    instock: true,
  },
  {
    id: 118,
    title: "Product 118",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 118",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 703912,
    instock: true,
  },
  {
    id: 119,
    title: "Product 119",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 119",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 520427,
    instock: true,
  },
  {
    id: 120,
    title: "Product 120",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 120",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 461017,
    instock: true,
  },
  {
    id: 121,
    title: "Product 121",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 121",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 344551,
    instock: true,
  },
  {
    id: 122,
    title: "Product 122",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 122",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 594788,
    instock: true,
  },
  {
    id: 123,
    title: "Product 123",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 123",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 489079,
    instock: true,
  },
  {
    id: 124,
    title: "Product 124",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 124",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 505884,
    instock: true,
  },
  {
    id: 125,
    title: "Product 125",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 125",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 242038,
    instock: true,
  },
  {
    id: 126,
    title: "Product 126",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 126",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 749713,
    instock: true,
  },
  {
    id: 127,
    title: "Product 127",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 127",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 394312,
    instock: true,
  },
  {
    id: 128,
    title: "Product 128",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 128",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 673633,
    instock: true,
  },
  {
    id: 129,
    title: "Product 129",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 129",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 557831,
    instock: true,
  },
  {
    id: 130,
    title: "Product 130",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 130",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 997819,
    instock: true,
  },
  {
    id: 131,
    title: "Product 131",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 131",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 385698,
    instock: true,
  },
  {
    id: 132,
    title: "Product 132",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 132",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 755071,
    instock: true,
  },
  {
    id: 133,
    title: "Product 133",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 133",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 907464,
    instock: true,
  },
  {
    id: 134,
    title: "Product 134",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 134",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 551519,
    instock: true,
  },
  {
    id: 135,
    title: "Product 135",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 135",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 128974,
    instock: true,
  },
  {
    id: 136,
    title: "Product 136",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 136",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 954579,
    instock: true,
  },
  {
    id: 137,
    title: "Product 137",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 137",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 967123,
    instock: true,
  },
  {
    id: 138,
    title: "Product 138",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 138",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 933678,
    instock: true,
  },
  {
    id: 139,
    title: "Product 139",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 139",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 514219,
    instock: true,
  },
  {
    id: 140,
    title: "Product 140",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 140",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 878742,
    instock: true,
  },
  {
    id: 141,
    title: "Product 141",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 141",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 465819,
    instock: true,
  },
  {
    id: 142,
    title: "Product 142",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 142",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 629102,
    instock: true,
  },
  {
    id: 143,
    title: "Product 143",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 143",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 732869,
    instock: true,
  },
  {
    id: 144,
    title: "Product 144",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 144",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 226655,
    instock: true,
  },
  {
    id: 145,
    title: "Product 145",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 145",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 323718,
    instock: true,
  },
  {
    id: 146,
    title: "Product 146",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 146",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 474890,
    instock: true,
  },
  {
    id: 147,
    title: "Product 147",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 147",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/01.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 372019,
    instock: true,
  },
  {
    id: 148,
    title: "Product 148",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 148",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 533718,
    instock: true,
  },
  {
    id: 149,
    title: "Product 149",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 149",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 260397,
    instock: true,
  },
  {
    id: 150,
    title: "Product 150",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 150",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 214093,
    instock: true,
  },
  {
    id: 151,
    title: "Product 151",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 151",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 189178,
    instock: true,
  },
  {
    id: 152,
    title: "Product 152",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 152",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 779395,
    instock: true,
  },
  {
    id: 153,
    title: "Product 153",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 153",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 496021,
    instock: true,
  },
  {
    id: 154,
    title: "Product 154",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 154",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 599700,
    instock: true,
  },
  {
    id: 155,
    title: "Product 155",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 155",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 458465,
    instock: true,
  },
  {
    id: 156,
    title: "Product 156",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 156",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 801087,
    instock: true,
  },
  {
    id: 157,
    title: "Product 157",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 157",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 513520,
    instock: true,
  },
  {
    id: 158,
    title: "Product 158",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 158",
    originalprice: 100,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 942389,
    instock: true,
  },
  {
    id: 159,
    title: "Product 159",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 159",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 995245,
    instock: true,
  },
  {
    id: 160,
    title: "Product 160",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 160",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 306332,
    instock: true,
  },
  {
    id: 161,
    title: "Product 161",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 161",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 954506,
    instock: true,
  },
  {
    id: 162,
    title: "Product 162",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 162",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 571055,
    instock: true,
  },
  {
    id: 163,
    title: "Product 163",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 163",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 267010,
    instock: true,
  },
  {
    id: 164,
    title: "Product 164",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 164",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 823660,
    instock: true,
  },
  {
    id: 165,
    title: "Product 165",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 165",
    originalprice: 150,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 908711,
    instock: true,
  },
  {
    id: 166,
    title: "Product 166",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 166",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 991352,
    instock: true,
  },
  {
    id: 167,
    title: "Product 167",
    rating: 2,
    description: "Lorem ipsum dolor sit amet for Product 167",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 133959,
    instock: true,
  },
  {
    id: 168,
    title: "Product 168",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 168",
    originalprice: 150,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/01.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 815712,
    instock: true,
  },
  {
    id: 169,
    title: "Product 169",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 169",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 198987,
    instock: true,
  },
  {
    id: 170,
    title: "Product 170",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 170",
    originalprice: 100,
    price: 100,
    image1: "img/products/05.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 148129,
    instock: true,
  },
  {
    id: 171,
    title: "Product 171",
    rating: 5,
    description: "Lorem ipsum dolor sit amet for Product 171",
    originalprice: 150,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/01.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/04.jpg",
    artikelnummer: 303922,
    instock: true,
  },
  {
    id: 172,
    title: "Product 172",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 172",
    originalprice: 100,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/05.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/02.jpg",
    artikelnummer: 436975,
    instock: true,
  },
  {
    id: 173,
    title: "Product 173",
    rating: 3,
    description: "Lorem ipsum dolor sit amet for Product 173",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 483852,
    instock: true,
  },
  {
    id: 174,
    title: "Product 174",
    rating: 1,
    description: "Lorem ipsum dolor sit amet for Product 174",
    originalprice: 100,
    price: 100,
    image1: "img/products/03.jpg",
    image2: "img/products/03.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/02.jpg",
    image5: "img/products/03.jpg",
    artikelnummer: 619040,
    instock: true,
  },
  {
    id: 175,
    title: "Product 175",
    rating: 4,
    description: "Lorem ipsum dolor sit amet for Product 175",
    originalprice: 150,
    price: 100,
    image1: "img/products/04.jpg",
    image2: "img/products/04.jpg",
    image3: "img/products/02.jpg",
    image4: "img/products/05.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 425258,
    instock: true,
  },
];

module.exports = products;
