const products = [
  {
    id: 1,
    title: "Product 1",
    rating: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 123456,
    instock: true,
  },
  {
    id: 2,
    title: "Product 2",
    rating: 3,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 150,
    price: 100,
    image1: "img/products/02.jpg",
    image2: "img/products/05.jpg",
    image3: "img/products/04.jpg",
    image4: "img/products/03.jpg",
    image5: "img/products/01.jpg",
    artikelnummer: 123456,
    instock: true,
  },
  {
    id: 3,
    title: "Product 3",
    rating: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 123456,
    instock: true,
  },
  {
    id: 4,
    title: "Product 4",
    rating: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 123456,
    instock: true,
  },
  {
    id: 5,
    title: "Product 5",
    rating: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 123456,
    instock: true,
  },
  {
    id: 6,
    title: "Product 6",
    rating: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 123456,
    instock: true,
  },
  {
    id: 7,
    title: "Product 7",
    rating: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 123456,
    instock: true,
  },
  {
    id: 8,
    title: "Product 8",
    rating: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 123456,
    instock: true,
  },
  {
    id: 9,
    title: "Product 9",
    rating: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 123456,
    instock: true,
  },
  {
    id: 10,
    title: "Product 10",
    rating: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rhoncus arcu turpis, quis sagittis orci dictum non. Etiam id eleifend erat. Donec sit amet nisl id nisi laoreet viverra in ac nibh.",
    originalprice: 100,
    price: 100,
    image1: "img/products/01.jpg",
    image2: "img/products/02.jpg",
    image3: "img/products/03.jpg",
    image4: "img/products/04.jpg",
    image5: "img/products/05.jpg",
    artikelnummer: 123456,
    instock: true,
  },
];

module.exports = products;
