import "../public/vendor/bootstrap/css/bootstrap.css";

import "../public/scss/styles.scss";
import "../public/css/styles.css";
import "../public/css/animate.css";
import "../public/css/owl-carousel.css";
import "../public/css/lightbox.css";
import "../public/css/jquery-ui.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@fontsource/playfair-display/400.css";
import "@fontsource/playfair-display/700.css";
import "@fontsource/playfair-display/900.css";

import "@fontsource/poppins/400.css";
import "@fontsource/poppins/500.css";
import "@fontsource/poppins/700.css";
import "@fontsource/poppins/900.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, shrink-to-fit=no",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Poppins:400,500,700,900"
          rel="stylesheet"
        />

        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>

      <body className={inter.className}>
        {children}

        <script defer src="js/jquery.min.js"></script>
        <script defer src="js/jquery-ui.min.js"></script>
        <script defer src="js/bootstrap.min.js"></script>
        <script defer src="js/owl.carousel.min.js"></script>
        <script defer src="js/parallax.js"></script>
        <script defer src="js/ResizeSensor.min.js"></script>
        <script defer src="js/theia-sticky-sidebar.min.js"></script>
        <script defer src="js/jquery.countdown.min.js"></script>
        <script defer src="js/masonry.pkgd.min.js"></script>
        <script defer src="js/imagesloaded.pkgd.min.js"></script>
        <script defer src="js/jquery.zoom.min.js"></script>
        <script defer src="js/custom.js"></script>
      </body>
    </html>
  );
}
