---
- name: Installeer Apache
  hosts: all
  tasks:
    - name: Installeer Apache
      yum:
        name: httpd
        state: latest
    - name: Start Apache
      service:
        name: httpd
        state: started

- name: installeer npm
  hosts: all
  tasks:
    - name: installeer npm
      yum:
        name: npm
        state: latest

- name: setup Apache voor react website met express server
  hosts: all
  become: true
  tasks:
    - name: httpd.conf from ansible to /etc/httpd/conf/httpd.conf (overwrite existing)
      synchronize:
        src: /vagrant/ansible/files/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        delete: no

    - name: refresh apache
      service:
        name: httpd
        state: restarted

    - name: Kill any running Node processes
      shell: "sudo fuser -k {{ item }}"
      failed_when: false # Ignore errors
      with_items:
        - 3000/tcp
        - 5000/tcp

    - name: "install the Node app depndencies"
      shell: sudo npm install
      args:
        chdir: /vagrant/ansible/bp-site

    - name: "build the Node app"
      shell: sudo npm run build
      args:
        chdir: /vagrant/ansible/bp-site

    - name: "Start the Node app"
      shell: nohup npm start &
      args:
        chdir: /vagrant/ansible//bp-site
