---
- name: Installeer Apache
  hosts: all
  tasks:
    - name: Installeer Apache
      yum:
        name: httpd
        state: latest
    - name: Start Apache
      service:
        name: httpd
        state: started

- name: installeer npm
  hosts: all
  tasks:
    - name: installeer npm
      yum:
        name: npm
        state: latest

- name: setup Apache voor react website met express server
  hosts: all
  become: true
  tasks:
    - name: httpd.conf from ansible to /etc/httpd/conf/httpd.conf (overwrite existing)
      synchronize:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        delete: no

    - name: refresh apache
      service:
        name: httpd
        state: restarted

    - name: Find the PID(s) of the process using port 3000
      shell: sudo netstat -tulnp | grep :3000
      register: pid_output
      ignore_errors: yes

    - name: Kill the process with the found PID
      shell: "kill {{ item }}"
      with_items: "{{ pid_output.stdout_lines }}"
      when: pid_output.stdout_lines

    - name: Find the PID(s) of the process using port 5000
      shell: sudo netstat -tulnp | grep :5000
      register: pid_output2
      ignore_errors: yes

    - name: Kill the process with the found PID
      shell: "kill {{ item }}"
      with_items: "{{ pid_output2.stdout_lines }}"
      when: pid_output2.stdout_lines

    - name: "Start the Node app"
      shell: nohup npm start &
      args:
        chdir: /vagrant/ansible/nextjs_react/bp-site
