---
- name: Configure the server with Apache and Node
  hosts: all
  tasks:
    - name: Install Apache and npm
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - npm

    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Copy the Apache config file
      ansible.builtin.copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: '0644'

    # - name: Kill any running Node processes
    #   ansible.builtin.shell: "sudo fuser -k {{ item }}"
    #   failed_when: false # Ignore errors
    #   with_items:
    #     - 3000/tcp
    #     - 5000/tcp

    # - name: "install the Node app dependencies"
    #   ansible.builtin.shell: sudo npm install
    #   args:
    #     chdir: /vagrant/ansible/React/bp-site


# - name: setup Apache voor react website met express server
#   hosts: all
#   become: true
#   tasks:


#     - name: refresh apache
#       service:
#         name: httpd
#         state: restarted


#     - name: "build the Node app"
#       shell: sudo npm run build
#       args:
#         chdir: /vagrant/ansible/React/bp-site

#     - name: "Start the Node app"
#       shell: nohup npm start &
#       args:
#         chdir: /vagrant/ansible/React/bp-site
