# containers.yml
---
- name: Build the Docker image
  community.docker.docker_image:
    name: "{{ item.name }}"
    build:
      path: "/home/vagrant/{{ item.source_dir }}"
    state: present
    force_source: true
    source: build
  with_items: "{{ container_sites }}"

- name: Start the Docker image
  community.docker.docker_container:
    name: "{{ item.name }}_container"
    image: "{{ item.name }}"
    state: started
    ports:
      - "{{ item.port }}:{{ item.port }}"
  with_items: "{{ container_sites }}"
