# site.yml
---
- name: Configure the server with Docker, Apache and Node
  hosts: all
  vars:
    pip_install_packages:
      - requests # Needed for the Ansible Docker modules
    docker_users:
      - vagrant # Allow the vagrant user to run Docker commands
    frontend_sites:
      - name: frontend
        port: 3001
        source_dir: frontend
      - name: frontend_Dynamische_CSS_Selectors
        port: 3002
        source_dir: frontend_Dynamische_CSS_Selectors
      - name: frontend_Dynamische_Tree_Structure
        port: 3003
        source_dir: frontend_Dynamische_Tree_Structure
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
  tasks:
    - name: Install Apache and npm
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - npm

    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Copy the source code
      ansible.posix.synchronize:
        src: "{{ item }}"
        dest: /home/vagrant/
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=.next"
      with_items:
        - frontend
        - frontend_Dynamische_CSS_Selectors
        - frontend_Dynamische_Tree_Structure
        - backend

    - name: Create an environment file
      ansible.builtin.copy:
        dest: /home/vagrant/{{ item }}/.env.local
        owner: vagrant
        group: vagrant
        mode: "0644"
        content: |
          NEXT_PUBLIC_API_URL=http://192.168.56.10:5000
      with_items:
        - frontend
        - frontend_Dynamische_CSS_Selectors
        - frontend_Dynamische_Tree_Structure

    - name: Build the backend Docker image
      community.docker.docker_image:
        name: backend
        state: present
        source: build
        force_source: true # Force rebuild
        build:
          path: /home/vagrant/backend

    - name: Start the backend container
      community.docker.docker_container:
        name: backend
        image: backend
        state: started
        ports:
          - 5000:5000

    - name: Configure and start frontend Apache servers
      ansible.builtin.include_tasks: frontend_apache.yml
      with_items: "{{ frontend_sites }}"
      loop_control:
        loop_var: frontend_site
