# site.yml
---
- name: Configure the Proof of Concept
  hosts: all
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
  tasks:
    - name: Copy the source code
      ansible.posix.synchronize:
        src: "{{ item }}"
        dest: /home/vagrant/
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=.next"
      with_items:
        - backend
        - backend_anti
        - frontend
        - frontend_dynamische_css_selectors
        - frontend_dynamische_tree_structure
        - frontend_server_anti
        - grafana-conf.ini

    - name: Create an environment file
      ansible.builtin.copy:
        dest: /home/vagrant/{{ item }}/.env.local
        owner: vagrant
        group: vagrant
        mode: "0644"
        content: |
          NEXT_PUBLIC_API_URL=http://192.168.56.10:5000
      with_items:
        - frontend
        - frontend_dynamische_css_selectors
        - frontend_dynamische_tree_structure

    - name: Create an environment file
      ansible.builtin.copy:
        dest: /home/vagrant/{{ item }}/.env.local
        owner: vagrant
        group: vagrant
        mode: "0644"
        content: |
          NEXT_PUBLIC_API_URL=http://192.168.56.10:5002
      with_items:
        - frontend_server_anti

    - name: Configure and start containers
      ansible.builtin.include_tasks: containers.yml

    - name: Configure and start resource monitoring
      ansible.builtin.include_tasks: monitoring.yml
