# site.yml
---
- name: Configure the server with Docker, Apache and Node
  hosts: all
  vars:
    pip_install_packages:
      - requests # Needed for the Ansible Docker modules
    docker_users:
      - vagrant # Allow the vagrant user to run Docker commands
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
  tasks:
    - name: Install Apache and npm
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - npm

    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Copy the Apache config file
      ansible.builtin.copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: "0644"

    - name: Copy the source code
      ansible.posix.synchronize:
        src: "{{ item }}"
        dest: /home/vagrant/
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=.next"
      with_items:
        - frontend
        - backend

    - name: Create an environment file
      ansible.builtin.copy:
        dest: /home/vagrant/frontend/.env.local
        owner: vagrant
        group: vagrant
        mode: "0644"
        content: |
          NEXT_PUBLIC_API_URL=http://192.168.56.10:5000

    - name: Build the backend Docker image
      community.docker.docker_image:
        name: backend
        state: present
        source: build
        force_source: true # Force rebuild
        build:
          path: /home/vagrant/backend

    - name: Start the backend container
      community.docker.docker_container:
        name: backend
        image: backend
        state: started
        ports:
          - 5000:5000

    - name: Build the frontend Docker image
      community.docker.docker_image:
        name: frontend
        state: present
        source: build
        force_source: true # Force rebuild
        build:
          path: /home/vagrant/frontend
          args:
            apiUrl: http://192.168.56.10:5000

    - name: Start the frontend container
      community.docker.docker_container:
        name: frontend
        image: frontend
        state: started
        ports:
          - 3000:3000
